### ISSUE TITLE
Converting pptx to pdf

### ISSUE THREAD

**Issue by aubertc** [csci-1301/csci-1301.github.io#52]
Thanks, @etremel , for adding the page with the slides and for working on them ( https://csci-1301.github.io/slides.html ).
I believe it would be beneficial to add `pdf` versions of those `pptx` files, for students that have access to pdf readers but not to Microsoft PowerPoint or similar software.

Using

```
libreoffice --headless --convert-to pdf Programming-Intro.pptx
```

I can obtain the file attached, that seems identical to the pptx file (although heavier).
[Programming-Intro.pdf](https://github.com/csci-1301/csci-1301.github.io/files/6994010/Programming-Intro.pdf)

@etremel Can you confirm that there is no noticeable difference?
@nkrusch , I would think that installing libreoffice will make a significant dent in the compilation time, maybe we can find a work-around by compiling and uploading them "locally", on our machines (I'm happy to add this bit in my backup workflow, that has to take place on my computer anyway).

**Comment by etremel** [comment]
When I taught the class last semester, I actually posted both PDF and PPTX versions of the slides to D2L, and I was planning to do the same thing this semester. I didn't realize that the slides in the repository were going to be made available on the website, which is why I didn't originally commit the PDF versions, but it's not too hard for me to do that now. It would be nice if there was an automated way to convert a PPTX to PDF every time I save it (to keep the two versions in sync), but for now, my workflow has always been to make changes in PowerPoint, save it twice (once in PPTX and once in PDF), then upload both copies.

**Comment by nkrusch** [comment]
Based on Edward's answer, I think the easiest solution would be to save twice in both formats whenever making edits.

**Comment by aubertc** [comment]
Ok perfect, thanks.
